#include "codegen/CodeGenerator.hpp"

namespace mr {

namespace {
const char *kArgRegs[6] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
}

void CodeGenerator::genFuncDecl(const NodeStmtFuncDecl &func) {
    const auto savedVars = _vars;
    const auto savedMarks = _scopeMarks;
    const auto savedStackSize = _stackSize;
    const StorageKind savedReturnKind = _currentFuncReturnKind;
    _vars.clear();
    _scopeMarks.clear();
    _stackSize = 0;
    _currentFuncReturnKind = resolveStorageKind(func.modifiers.type);
    _inFunction = true;

    _out << "func_" << func.name << ":\n";
    _out << "    push rbp\n    mov rbp, rsp\n";
    beginScope();
    for (std::size_t i = 0; i < func.params.size(); ++i) {
        push(kArgRegs[i], "param " + func.params[i]->name);
        _vars.push_back(
            Var{func.params[i]->name,
                false,
                i,
                {},
                resolveStorageKind(func.params[i]->modifiers.type)});
    }
    for (const NodeStmt *stmt : func.body->stmts) { genStmt(*stmt); }
    endScope();
    _out << "    mov rsp, rbp\n    pop rbp\n    ret\n\n";

    _inFunction = false;
    _vars = savedVars;
    _scopeMarks = savedMarks;
    _stackSize = savedStackSize;
    _currentFuncReturnKind = savedReturnKind;
}

void CodeGenerator::genFunctions() {
    for (const NodeStmt *stmt : _program.stmts) {
        if (std::holds_alternative<NodeStmtFuncDecl *>(stmt->var)) {
            genFuncDecl(*std::get<NodeStmtFuncDecl *>(stmt->var));
        }
    }
}

void CodeGenerator::genEntryPoint() {
    _out << "_start:\n";
    for (const NodeStmt *stmt : _program.stmts) {
        if (!std::holds_alternative<NodeStmtFuncDecl *>(stmt->var)) {
            genStmt(*stmt);
        }
    }
    _out << "    ; implicit program exit (status 0) if execution falls "
            "through\n";
    _out << "    mov rax, 60\n    mov rdi, 0\n    syscall\n\n";
}


std::string CodeGenerator::generate() {
    collectFunctionSignatures();
    _out << "default abs    ; silences NASM's implicit-default-ABS deprecation "
            "warning\n";
    _out << "; Generated by the mr compiler - do not edit by hand.\n";
    _out << "global _start\n";
    _out << "section .text\n";
    genEntryPoint();
    genFunctions();
    emitPrintIntRoutine();
    emitPrintStrRoutine();
    emitPrintCharRoutine();
    emitPrintFloatRoutine();
    emitStrConcatRoutine();
    emitCharToStrRoutine();
    emitIntToStrRoutine();

    _out << "\nsection .rodata\n";
    _out << "    nl_byte: db 10\n";
    _out << _rodata.str();

    _out << "\nsection .bss\n";
    _out << "    str_heap: resb 65536    ; bump-allocated runtime string "
            "arena, see str_concat\n";
    _out << "    str_heap_offset: resq 1\n";
    _out << _staticData.str();
    return _out.str();
}

}  // namespace mr